site_name: Glacier
theme:
  name: readthedocs
  highlightjs: true
  logo: img/logo.svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Codes:
      - Motivation: 1_codes/1_motivation.md
      - Installation: 1_codes/2_installation.md
  - Workshop:
      - Motivation: 2_workshop/1_motivation.md
  - Cyber learning tools:
      - Motivation: 3_cyber_learning_tools/1_motivation.md
